name: Reclutamiento de agente

on: push

jobs:
   reporte-de-reclutamiento:
      runs-on: ubuntu-latest
      steps:
         

         - name: El agente se presenta
           run: echo "Hola Mundo..."

         - name: Reporte de identidad
           run: |
              echo "Reporte de idenctidad"
              echo "====================="
              echo ""
              echo "Nombre en clave: ${{ github.actor }}"
              echo "Repo: ${{ github.repository }}"
              echo "Operacion: ${{ github.sha }}"
              echo "Matedata: ${{ toJson(github) }}"
              